### PR TITLE
Add setuptools etc. to host

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge-admin, please rerender

**Comment by thewchan** [comment]
@dopplershift 
PR is here

**Comment by thewchan** [comment]
@alexmojaki Hi just adding this host dependency because without them it's causing some error for packages that uses `pure_eval` as a dependency downstream

**Comment by alexmojaki** [comment]
Thanks! Is there a discussion in an issue or something that led to this? Just so that I have some background to refer to.

Both pure_eval and stack_data support Python 3.5, so I'm a little worried that you've changed some lines to `python >=3.6`. Will that affect Python 3.5 users? Is it hard to make the build work without the change? If it is, I can accept that.

@Anthchirp if you could take a look at this and https://github.com/conda-forge/stack_data-feedstock/pull/2 I'd appreciate it. You don't have to of course, but it looks like your PR https://github.com/conda-forge/executing-feedstock/pull/3 solved a similar problem and is probably the only reason the `executing` feedstock doesn't need another PR just like these two, and the three packages are closely related. Meanwhile, I don't know what all these changes mean.

**Comment by dopplershift** [comment]
Only the changes to `meta.yml` need to be evaluated. The rest of that came in with "re-rendering" the feedstock. 

The motivation on [this PR](https://github.com/conda-forge/staged-recipes/pull/17509) is that `pip check` was detecting `stack-data` and `pure-eval` as version 0.0.0--ostensibly due to setuptools_scm missing when the package was built. I don't know the motivation for changing to Python 3.6, so I'll let @thewchan speak to that. I will say that while conda-forge doesn't build for Python 3.6 any more, this being noarch means there's no conda-forge reason to drop it.

**Comment by thewchan** [comment]
I can put it back down to 3.5; I'm merely referring to grayskull's output. Adding setuptools is prompted by this: https://github.com/conda-forge/staged-recipes/pull/17509

**Comment by thewchan** [comment]
I looked at the `executing` PR linked and I guess adding the `pip check` test here wouldn't be a bad idea? I can do that as well if that's okay?

**Comment by alexmojaki** [comment]
Go ahead

**Comment by alexmojaki** [comment]
Great! Are you ready for me to merge them both? Does the bot need to rerender again?

**Comment by dopplershift** [comment]
No rerender necessary at this point.

**Comment by thewchan** [comment]
@alexmojaki @dopplershift this is ready to go; happy to make more changes if needed

**Comment by alexmojaki** [comment]
Thanks!

It's cool that you're making a feedstock for friendly. What are you using it for?

**Comment by thewchan** [comment]
To be honest I haven't had plans on using it personally; but I think it's a very cool project and I'm just trying to bring it over to conda-forge for wider exposure

**Comment by Anthchirp** [comment]
Hi, all changes look good, also in the reference PR. If you know that the package still supports Python 3.5 then it's absolutely fine to keep the `>=3.5` in there, if you're not entirely sure then it'd also have been okay to increase that to the minimum supported version, which these days would be `>=3.7`. The resulting package is mostly the same, because of `noarch` as mentioned, but I believe the version restriction would still mean that old python users would not be offered the upgrade.

Thanks for contributing to conda-forge :slightly_smiling_face:

**Pull request merged**
